[project]
name = 'Transparent-Charity-Donation-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.donation-management]
path = 'contracts/donation-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.donor-recognition-nft]
path = 'contracts/donor-recognition-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
